export const MODES = {
  futevolei: {
    surface: "sand",
    name: "Futevôlei",
    players: 2,
    keeper: false,
    footvolley: true,
    halfLength: 9,
    halfWidth: 4.5,
    goalHalf: 0,
    goalHeight: 0,
    color: "#ed6ba7",
  },
  altinha: {
    surface: "sand",
    name: "Altinha",
    players: 4,
    keeper: false,
    altinha: true,
    halfLength: 19,
    halfWidth: 12,
    goalHalf: 0,
    goalHeight: 0,
    color: "#f6bc7b",
  },
  duel: {
    surface: "court",
    name: "Gol a gol",
    players: 1,
    keeper: true,
    duel: true,
    halfLength: 20,
    halfWidth: 10,
    goalHalf: 1.5,
    goalHeight: 2,
    apron: 8,
    color: "#e8a36d",
  },
  match: {
    surface: "grass",
    name: "Campo",
    players: 11,
    keeper: true,
    halfLength: 46,
    halfWidth: 30,
    goalHalf: 3.66,
    goalHeight: 2.44,
    color: "#55c878",
  },
  street: {
    surface: "street",
    name: "Rua",
    players: 3,
    keeper: false,
    halfLength: 19.2,
    halfWidth: 5.175,
    curbHeight: 0.22,
    goalStyle: "crate",
    goalHalf: 0.72,
    goalHeight: 0.9,
    color: "#687c85",
  },
  sand: {
    surface: "sand",
    name: "Areia",
    players: 5,
    keeper: true,
    halfLength: 19,
    halfWidth: 12,
    goalHalf: 2.75,
    goalHeight: 2.2,
    color: "#f5cd83",
  },
  court: {
    surface: "court",
    name: "Quadra",
    players: 5,
    keeper: true,
    halfLength: 20,
    halfWidth: 10,
    goalHalf: 1.5,
    goalHeight: 2,
    color: "#38b9bc",
  },
};
export const modeConfig = (id) => MODES[id] || MODES.match;
